name: Build

on:
  push:
    branches:
      - master
      - release/**
    # tags:
    #   - v*.*.*
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [10.x, 12.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup display
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"
        if: contains(matrix.os, 'ubuntu')

      - name: Install
        run: npm ci
        env:
          CI: true

      - name: Check formatting
        run: npm run format
        env:
          CI: true

      - name: Build and test
        run: |
          npm run compile
          npm run test
        env:
          CI: true
          DISPLAY: ":99.0"

      - name: Package
        run: |
          npm run package
        env:
          CI: true
