name: Cherry Pick

on: repository_dispatch

jobs:
  cherry-pick:
    if: ${{ github.event.client_payload.slash_command.args.command == 'cherry-pick'}}
    runs-on: ubuntu-latest
    steps:
      - name: "Dump payload context"
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.slash_command.args.named.branch }}
      # switch to target branch
      # - name: Cherry Pick
      #   run: |
      #     git cherry-pick ...
      # - name: Push
      #   shell: git push origin ...
      # open a pull request from pushed branch into target branch
